# Generated by Django 3.2.5 on 2021-11-22 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=50)),
                ('product_quantity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='budgets.budget')),
            ],
        ),
    ]
