# Generated by Django 3.2.5 on 2021-11-22 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_budget_items'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Budget_items',
            new_name='Budget_item',
        ),
    ]
