# Generated by Django 3.2.5 on 2021-11-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0003_rename_budget_items_budget_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget_item',
            name='product_price',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='budget_item',
            name='product_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
