# Generated by Django 3.2.5 on 2021-11-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0005_auto_20211122_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget_item',
            name='product_quantity',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=8),
        ),
    ]
