# Generated by Django 3.2.5 on 2021-11-16 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20211106_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.DecimalField(decimal_places=0, max_digits=5)),
                ('project', models.CharField(max_length=50)),
                ('client', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.DecimalField(decimal_places=0, max_digits=5)),
                ('address', models.CharField(max_length=50)),
                ('client', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Budget_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('budget_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.budget')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.product')),
            ],
        ),
    ]
