# Generated by Django 3.2.5 on 2021-11-17 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_budget_budget_items_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='number',
            field=models.CharField(max_length=50),
        ),
    ]
