# Generated by Django 3.2.5 on 2021-11-18 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_project_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
